// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRpVfaFrjIp74l-pkSMvNvBCopSQrhwV4',
    appId: '1:536780966931:web:a99c36166f69632b9783e6',
    messagingSenderId: '536780966931',
    projectId: 'guidemania2024',
    authDomain: 'guidemania2024.firebaseapp.com',
    databaseURL: 'https://guidemania2024-default-rtdb.firebaseio.com',
    storageBucket: 'guidemania2024.appspot.com',
    measurementId: 'G-26SHWE1WY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE1sSxjMguaMA4DJ5zGXfzEirjpNpTG-U',
    appId: '1:536780966931:android:fc94afbf633e4dde9783e6',
    messagingSenderId: '536780966931',
    projectId: 'guidemania2024',
    databaseURL: 'https://guidemania2024-default-rtdb.firebaseio.com',
    storageBucket: 'guidemania2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvXjbqvJuSKhbtXevZ-k5Rf1ip6QJ-_k',
    appId: '1:536780966931:ios:aba841f4048c30e49783e6',
    messagingSenderId: '536780966931',
    projectId: 'guidemania2024',
    databaseURL: 'https://guidemania2024-default-rtdb.firebaseio.com',
    storageBucket: 'guidemania2024.appspot.com',
    iosBundleId: 'com.example.guide',
  );
}
